- uses: AndreasAugustin/actions-template-sync@v2
  with:
    source_repo_path: StageDog/tavern_helper_template
    pr_title: '[bot] 同步模板仓库的更新'
    pr_commit_msg: '[bot] bump template repository update'
    is_pr_cleanup: true
    template_sync_ignore_file_path: .github/.templatesyncignore
    is_force_deletion: false
    git_remote_pull_params: --allow-unrelated-histories --strategy=recursive --no-edit -X diff-algorithm=minimal -X ignore-all-space -X patience -X renormalize
